In [50]:
import torch

In [51]:
def activation(x):
    return 1/(1+torch.exp(-x))
torch.manual_seed(7)
features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

y =activation(torch.mm(features, weights.view(5,1)) + bias)
y

tensor([[0.1595]])

In [52]:
torch.manual_seed(7) 
features = torch.randn((1, 3))
n_input = features.shape[1]     
n_hidden = 2                    
n_output = 1                  
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

h = activation(torch.mm(features, W1) +B1)
output = activation(torch.mm(h,W2)+B2)
print(output)

tensor([[0.3171]])


In [53]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.66916635, 0.12259644, 0.02353964],
       [0.05006167, 0.93278736, 0.94765373],
       [0.60917922, 0.98868574, 0.30090627],
       [0.64584352, 0.06403492, 0.85141404]])

In [23]:
b = torch.from_numpy(a)
b

tensor([[0.1603, 0.3047, 0.0900],
        [0.7062, 0.4474, 0.2317],
        [0.5567, 0.4738, 0.8348],
        [0.2748, 0.5957, 0.4978]], dtype=torch.float64)

In [24]:
b.numpy()

array([[0.16030825, 0.30467122, 0.0899595 ],
       [0.7061931 , 0.44743853, 0.23168494],
       [0.55668956, 0.4738463 , 0.83479247],
       [0.27479552, 0.59566155, 0.49778853]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [25]:
b.mul_(2)

tensor([[0.3206, 0.6093, 0.1799],
        [1.4124, 0.8949, 0.4634],
        [1.1134, 0.9477, 1.6696],
        [0.5496, 1.1913, 0.9956]], dtype=torch.float64)

In [54]:
a

array([[0.66916635, 0.12259644, 0.02353964],
       [0.05006167, 0.93278736, 0.94765373],
       [0.60917922, 0.98868574, 0.30090627],
       [0.64584352, 0.06403492, 0.85141404]])

In [55]:
print(torch.manual_seed)

<function manual_seed at 0x7fb7c62a7670>


In [ ]:
print()